{% set name = "inflate64" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/inflate64-{{ version }}.tar.gz
  sha256: b52dd8fefd2ba179e5dfa18d6eca7e2fc822584616271c039d5ef1f9ca90c71c

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - importlib-metadata  # [py<38]
    - python

test:
  imports:
    - inflate64
  commands:
    - pip check
  requires:
    - pip

about:
  description: A python package to provide Deflater and Inflater class to compress and decompress with Enhanced Deflate compression algorithm.
  home: https://pypi.org/project/inflate64/
  dev_url: https://codeberg.org/miurahr/inflate64
  doc_url: https://codeberg.org/miurahr/inflate64/src/branch/main/README.rst
  summary: deflate64 compression/decompression library
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file:
    - COPYING

extra:
  recipe-maintainers:
    - sarthakpati
